function run_test()

% RUN_TEST executes a series of test functions to check for the integrity
% of the tutorials and the downloaded data. It is based on the assumption
% that the test functions reflect the MATLAB-code in the tutorials (which
% is not a given). Also it assumes that the company download_data()
% function has been executed, and that the downloaded data corresponds
% witht he executed tutorials below. This function is for the 2026 edition
% of the MEG-OPM toolkit, which intends to run the following tutorials:
%
% test_tutorial_eventrelatedaveraging
% test_tutorial_clusterpermutationtimelock
% test_tutorial_beamformer
% test_tutorial_denoising_opm
% test_tutorial_preprocessing_opm
% test_tutorial_coregistration_opm
% test_tutorial_opm_helmet_design
%
% In its functional behavior it is expected that run_test() is called from
% within a .test folder, which resides in a folder that also contains a
% fieldtrip folder, and a folder called data, as generated by the
% download_data function
%
% _ .test
% |   |_run_test()
% |   |_download_data()
% |_fieldtrip-<somedate>
% |_data
%     |_Subject01.ds
%     |_<etc>
%

pwdir = pwd;

filename  = mfilename('fullpath');
filename  = strrep(filename, '.test', 'somethingirrelevant'); %fileparts does not like the hidden directory
[p, f, e] = fileparts(filename);
basedir   = strrep(p, 'somethingirrelevant', '');
cd(basedir);

d = dir('fieldtrip*');
if ~isempty(d)
  cd(d(1).name);
  ft_defaults;
  global ft_default;
  ft_default.checkconfig = 'loose'; % to avoid too pedantic cfg checking causing errors
end
cd(basedir);
addpath('.test');

[ftver, ftpath] = ft_version;
[p, f, e]       = fileparts(ftpath);
datapath        = fullfile(p, 'data');

test_tutorial_eventrelatedaveraging(fullfile(datapath, 'Subject01.ds')); close all;
test_tutorial_clusterpermutationtimelock(fullfile(datapath, 'Subject01.ds'), fullfile(datapath, 'cluster_permutation_timelock')); close all;
test_tutorial_beamformer(fullfile(datapath, 'beamformer')); close all;
test_tutorial_denoising_opm(fullfile(datapath, 'denoising_opm/sub-001/ses-opm01/meg')); close all;
test_tutorial_preprocessing_opm(fullfile(datapath, 'preprocessing_opm')); close all;
test_tutorial_coregistration_opm(fullfile(datapath, 'coregistration_opm')); close all;
test_tutorial_opm_helmet_design(fullfile(datapath, 'opm_helmet_design')); close all;

cd(pwdir);
